title: Deliverybot
description: >-
  Simple Deployment Automation
long_description: >-
  The easiest way to get started with deploying to Kubernetes, Google Cloud, AWS
  and more using GitHub. Stop building custom pipelines or scripts and get back
  to what matters.


deliverybot_url: https://app.deliverybot.dev
github_app_url: https://github.com/apps/deliverybot
github_org_url: https://github.com/deliverybot
terms_url: /terms/terms
privacy_url: /terms/privacy

terms:
  privacy_email: TODO
  support_email: TODO
  company: Deliverybot Software
  service: Deliverybot

baseurl: ""
url: https://deliverybot.dev
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: pretty
highlighter: rouge

plugins:
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
