title: Deliverybot
description: >-
  Simple Deployment Automation
long_description: >-
  The easiest way to deploy your code from GitHub.

deliverybot_url: https://app.deliverybot.dev
github_app_url: https://github.com/apps/deliverybot
github_org_url: https://github.com/deliverybot
terms_url: /terms/terms
privacy_url: /terms/privacy

privacy_email: support@deliverybot.dev
support_email: support@deliverybot.dev
corp_name: Deliverybot
service_name: Deliverybot

baseurl: ""
url: https://deliverybot.dev
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: pretty
highlighter: rouge

plugins:
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
