title: deliverybot
description: >-
  Simple Continuous Delivery for GitHub
long_description: >-
  Fast, safe and secure Continous Delivery pipelines you can setup in minutes.
  Powered by open source.

twitter:
  username: deliverybotdev
  card: summary
logo: /assets/logo.png
image: /assets/logo.png
author:
  twitter: deliverybotdev
social:
  name: Deliverybot
  links:
    - https://twitter.com/deliverybotdev

deliverybot_url: https://app.deliverybot.dev
github_app_url: https://github.com/apps/deliverybot
github_install_url: https://github.com/apps/deliverybot/installations/new
github_org_url: https://github.com/deliverybot
spectrum_url: https://spectrum.chat/deliverybot/general
start_url: https://github.com/apps/deliverybot/installations/new
slack_url: https://app.deliverybot.dev/slack/install
pricing_url: https://github.com/marketplace/deliverybot#marketplace-plans-container
twitter_url: https://twitter.com/deliverybotdev

terms_url: /terms/terms
privacy_url: /terms/privacy

privacy_email: privacy@deliverybot.dev
support_email: support@deliverybot.dev
corp_name: Deliverybot
service_name: Deliverybot

baseurl: ""
url: https://deliverybot.dev
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: pretty
highlighter: rouge

plugins:
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
