title: Deliverybot
description: >-
  Simple GitHub Continuous Delivery
long_description: >-
  Deploy your code using GitHub API's. Automatic deployments, PR deployments
  and integrations for any service. Powered by open source.

kubernetes_description: >-
  Continuous Delivery for Kubernetes
kubernetes_long_description: >-
  Deploy your code to Kubernetes using GitHub API's. Automatic deployments,
  PR deployments and more. Powered by open source.

deliverybot_url: https://app.deliverybot.dev
github_app_url: https://github.com/apps/deliverybot
github_install_url: https://github.com/apps/deliverybot/installations/new
github_org_url: https://github.com/deliverybot
spectrum_url: https://spectrum.chat/deliverybot/general
start_url: https://github.com/marketplace/deliverybot#marketplace-plans-container
slack_url: https://app.deliverybot.dev/slack/install
pricing_url: https://github.com/marketplace/deliverybot#marketplace-plans-container

terms_url: /terms/terms
privacy_url: /terms/privacy

privacy_email: privacy@deliverybot.dev
support_email: support@deliverybot.dev
corp_name: Deliverybot
service_name: Deliverybot

baseurl: ""
url: https://deliverybot.dev
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: pretty
highlighter: rouge

plugins:
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
