title: Deliverybot
description: >-
  Automate your deployments
long_description: >-
  Deliverybot automates simple and complex deployment workflows. Stop building
  custom pipelines or figuring out deployment scripts. Pick community driven
  recipes and get back to building.

deliverybot_url: https://app.deliverybot.dev
github_app_url: https://github.com/apps/deliverybot
github_org_url: https://github.com/deliverybot
terms_url: /terms/terms
privacy_url: /terms/privacy

terms:
  privacy_email: TODO
  support_email: TODO
  company: Deliverybot Software
  service: Deliverybot

baseurl: ""
url: https://deliverybot.dev
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: pretty
highlighter: rouge

plugins:
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
