title: deliverybot
email: your-email@example.com
description: >-
  The missing deployment automation tool for GitHub. Build
long_description: >-
  The missing deployment automation tool for GitHub. Build

deliverybot_url: https://deliverybot-ohzjlus46a-uc.a.run.app/
github_app_url: https://github.com/apps/deliverybot
baseurl: ""
url: https://deliverybot.github.io
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
